server:
  port: 80
# SpringBoot静态资源存放位置
# templates用来存放Thymeleaf 的页面。SpringBoot不推荐使用jsp
# classpath:/META‐INF/resources/
# classpath:/resources/
# classpath:/static/
# classpath:/public/
# 自定义静态资源位置
spring:
  web:
    resources:
      static-locations: classpath:/suibian/,classpath:/static/
