server:
  port: 80
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    mode: HTML5
    servlet:
      content-type: text/html
    encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/

