#端口
server:
  port: 80

spring:
  #thymeleaf
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
  #使用Spring Boot 默认的HikariDataSource 数据源  包:com.zaxxer.hikari
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    #使用自定义的数据源
    type: com.alibaba.druid.pool.DruidDataSource
  web:
    resources:
      static-locations: classpath:/static/