server:
  port: 80
#邮件配置
spring:
  thymeleaf:
    encoding: UTF-8
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: USERNAME
    password: PASSWORD
    port: 465
    protocol: smtp
    #启用SSL
    properties:
      mail:
        smtp:
          ssl:
            enable: true

#一些可用于产靠的原生属性
#spring.mail.properties.mail.smtp.ssl.enable=true
#spring.mail.properties.mail.smtp.socketFactory.port=465
#spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
