server:
  port: 80
spring:
  # freemarker后缀添加
  freemarker:
    suffix: .ftl
      # 设置文档类型
    content-type: text/html
      # 设置页面编码格式
    charset: UTF-8
      # 设置页面缓存
    cache: false
      #FreeMarker默认放在templates文件夹中，否则访问不到，放在其他目录需要配置下列参数。
    template-loader-path: classpath:/static/,classpath:/templates/
  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/