server:
  port: 8080
spring:
  #配置数据库数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

#MyBatis映射配置文件没有放在Mapper包下而是放在Resources目录下时的配置
#mybatis:
  #扫描classpath中mapper目录下的映射配置文件
#  mapper-locations: classpath:/mapper/*.xml
  #别名配置。使用pojo时可以直接使用pojo的类型不用加包名
#  type-aliases-package: cn.smart.pojo


  thymeleaf:
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
  web:
    resources:
      static-locations: classpath:/img/,classpath:/static/

#开启MyBatisMapperSQL语句的控制台显示
logging:
  level:
    com.wyfx.mg.dao.mapper: DEBUG

# PageHelper分页插件配置
pagehelper:
  #分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。
  helper-dialect: mysql
  #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  support-methods-arguments: true
  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum。
  params: count=countSql